basic_settings:
  site_title: Marion Müller LL.M. // Rechtsbegleitung, Mediation & Supervision in Köln
  favicon_image: /images/favicon.ico
  description: Konfliktsituationen begleiten uns ein Leben lang. Manchmal finden die Betroffenen weder einen einfachen noch einen friedlichen Lösungsweg. Lassen Sie uns gerne darüber reden. 


advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""