basic_settings:
  site_title: Marion Müller // Rechtsbegleitung, Mediation & Supervision in Köln
  favicon_image: /images/favicon.ico
  description: Willkommen auf meiner Web-Visitenkarte. Welche berufliche Adresse darf Ihnen der Mensch mit dem Namen Marion Müller anbieten? Sie können die Leistungen und Kompetenzen einer Rechtsanwältin, Mediatorin und Supervisorin wählen. Gerne biete ich Ihnen konstruktiv und zielführend meine Leistungen an. Wir werden im Rahmen meiner Begleitung aufgefordert sein, für Ihr konkretes Anliegen eine eigenverantwortliche Lösung zu finden.


advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""